print("Hallo klasgenoot ik ben Zarko Djurdjevic wat is jou naam")
naam = input()
print(naam + " " + "hoe oud ben jij?")
leeftijd = input()
print("------------------------------------------------------------")
print("hoe vond je de eerste paar weken tot nu toe op het MA?")
antwoord = input()
print("------------------------------------------------------------")
print("mooi antwoord")
print("------------------------------------------------------------")
print("wat is de reden dat je specifiek voor het MA hebt gekozen?")
antwoord = input()
print("------------------------------------------------------------")
print("Niceeeee")

